# This workflow will build a Java project with Gradle, create repository tag, and push a new docker image to docker hub
name: Create Tag and Push Image to DockerHub

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'metrics/**'
      - '**/*.md'
      - '*.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      APP_IMAGE: sasanlabs/owasp-vulnerableapp
      BASE_IMAGE: sasanlabs/owasp-vulnerableapp-base
    steps:
      - name: Checkout new changes
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262  # v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9  # v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130  # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f  # v3

      - name: Setup GitVersion action
        uses: gittools/actions/gitversion/setup@62f943a7b7e1981bb87a8314f304524657551786  # v0.9.7
        with:
          versionSpec: '5.x'

      - name: Execute GitVersion action
        id: gitversion
        uses: gittools/actions/gitversion/execute@62f943a7b7e1981bb87a8314f304524657551786  # v0.9.7

      - name: Create tag for GitHub
        uses: tvdias/github-tagger@a570476cc87352c1655c606b29590df6014535e0  # v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: '${{ steps.gitversion.outputs.semver }}'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and push base image
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8  # v6
        with:
          context: .
          file: ./Dockerfile.base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.BASE_IMAGE }}:${{ steps.gitversion.outputs.semver }}
            ${{ env.BASE_IMAGE }}:latest

      - name: Build with Gradle and push app image
        run: |
          ./gradlew jib \
            -Djib.to.image=${APP_IMAGE}:unreleased \
            -Djib.to.tags=${{ steps.gitversion.outputs.semver }},latest
