# This workflow will build a Java project with Gradle, create repository tag, and push a new docker image to docker hub
name: Create Tag and Push Image to DockerHub

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'metrics/**'
      - '**/*.md'
      - '*.md'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      APP_IMAGE: sasanlabs/owasp-vulnerableapp
      BASE_IMAGE: sasanlabs/owasp-vulnerableapp-base
    steps:
      - name: Checkout new changes
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - name: Login to DockerHub
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3

      - name: Setup GitVersion action
        uses: gittools/actions/gitversion/setup@65b583d16e32e5f06804e54ccbf9f05e1e1ca517 # v0.9.7
        with:
          versionSpec: '5.x'

      - name: Execute GitVersion action
        id: gitversion
        uses: gittools/actions/gitversion/execute@65b583d16e32e5f06804e54ccbf9f05e1e1ca517 # v0.9.7

      - name: Create tag for GitHub
        uses: tvdias/github-tagger@ed7350f67b0b8cbc4a3c1eae5cb0cb4c8ce4eec8 # v0.0.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          tag: '${{ steps.gitversion.outputs.semver }}'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build and push base image
        uses: docker/build-push-action@ca052bb54ab0790a636c9b5f226502c73d547a25 # v6
        with:
          context: .
          file: ./Dockerfile.base
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.BASE_IMAGE }}:${{ steps.gitversion.outputs.semver }}
            ${{ env.BASE_IMAGE }}:latest

      - name: Build with Gradle and push app image
        run: |
          ./gradlew jib \
            -Djib.to.image=${APP_IMAGE}:unreleased \
            -Djib.to.tags=${{ steps.gitversion.outputs.semver }},latest
